### ISSUE TITLE
How I get focus, focus out event?

### ISSUE THREAD

**Issue by ChangJoo-Park** [lukebrenton/ember-cli-medium-editor#6]
I want some dom change when out of editor.
How can I do this?

**Comment by lukebrenton** [comment]
Hi @ChangJoo-Park. There is probably a better way to do this but for now you can override my didInsertElement hook with one in your own component. You will have to create your own component that will look something like this:

```
import Ember from 'ember';
import MediumContentEditable from 'ember-cli-medium-editor/components/medium-content-editable';

export default MediumContentEditable.extend({
  didInsertElement: function() {
    var editor = new MediumEditor(this.$(), this.get('options'));
    editor.subscribe('focus', function (event, editable) {
      console.log(event, 'focus');
    });
    editor.subscribe('blur', function (event, editable) {
      console.log(event, 'blur');
    });

    return this.setContent();
  }
});
```

You will then have to use this new component in your template instead of  `{{ medium-content-editable }}`

**Comment by ChangJoo-Park** [comment]
@lukebrenton  thank you :+1:  I'll do it
